version: "3.8"
services:

  # PHP service
  app:
    build: ../../../../app
    container_name: symfony-amplify
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - symfony-amplify

  # MySQL database service
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    networks:
      - symfony-amplify

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: php-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge