version: "3.8"
services:
    php:
        build: app
        working_dir: /var/www/html
        volumes:
            - app/:/var/www/html
        networks:
            - amplify
    nginx:
        build: nginx
        working_dir: /var/www/html
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - app/:/var/www/html
        links:
            - php
        networks:
            - amplify
networks:
    amplify: